# Generated by Django 4.0 on 2022-04-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_filmwork_created_filmwork_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='age_rating',
            field=models.CharField(choices=[('G', 'G: General audience'), ('PG', 'PG: Parental guidance suggested'), ('PG-13', 'PG-13: Parents cautioned'), ('R', 'R: Restricted'), ('NC-17', 'NC-17: Adults only')], default='G', max_length=31, verbose_name='age rating'),
        ),
    ]
