# Generated by Django 4.0 on 2022-04-18 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_filmwork_age_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmwork',
            old_name='creation_date',
            new_name='release_date',
        ),
    ]
