# Generated by Django 4.0 on 2022-06-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_rename_creation_date_filmwork_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='access_type',
            field=models.CharField(choices=[('public', 'Public'), ('subscription', 'Subscription')], default='public', max_length=31, verbose_name='access type'),
        ),
    ]
